postprocess:
  data_layout: NHWC
preprocess:
  crop:
  - 512
  - 512
  data_layout: NHWC
  mean:
  - 127.5
  - 127.5
  - 127.5
  resize:
  - 512
  - 512
  scale:
  - 0.00784313725490196
  - 0.00784313725490196
  - 0.00784313725490196
session:
  artifacts_folder: ''
  model_folder: model
  model_path: handsfree_charging_v0_0.tflite
  session_name: tflitert
target_device: pc
task_type: segmentation
